# Generated by Django 6.0.4 on 2026-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='variant_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
