# Generated by Django 6.0.4 on 2026-07-20 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_movement_variant_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='users.productvariant'),
        ),
    ]
