# Generated by Django 6.0.4 on 2026-07-21 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sale_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('product', 'Product'), ('user', 'User'), ('chat', 'Chat'), ('transfer', 'Transfer'), ('movement', 'Movement'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.movement'),
        ),
    ]
