# Generated by Django 6.0.4 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def backfill_active_subscriptions(apps, schema_editor):
    AdminProfile = apps.get_model('users', 'AdminProfile')
    Subscription = apps.get_model('users', 'Subscription')
    for admin_profile in AdminProfile.objects.filter(subscription__isnull=True):
        Subscription.objects.create(admin_profile=admin_profile, status='active')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('magasin', 'Magasin'), ('employer', 'Employer'), ('platform_admin', 'Platform Admin')], default='employer', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('disabled', 'Désactivé'), ('pending', 'En attente'), ('trial', 'Essai (1 mois)'), ('demo', 'Démo')], default='pending', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.adminprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_updates', to='users.customuser')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.RunPython(backfill_active_subscriptions, noop_reverse),
    ]
