# Generated by Django 6.0.4 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


def cleanup_duplicate_companies(apps, schema_editor):
    AdminProfile = apps.get_model('users', 'AdminProfile')
    MagasinProfile = apps.get_model('users', 'MagasinProfile')

    for admin_profile in list(AdminProfile.objects.all()):
        owns_primary = MagasinProfile.objects.filter(admin=admin_profile.user).exists()
        is_coadmin_elsewhere = MagasinProfile.objects.filter(
            admins=admin_profile.user
        ).exclude(admin=admin_profile.user).exists()
        if not owns_primary and is_coadmin_elsewhere:
            admin_profile.delete()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscription_platform_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to='users.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(cleanup_duplicate_companies, noop_reverse),
    ]
