# Generated by Django 6.0.4 on 2026-07-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscriptionoffer_device_platformrequest_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrequest',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='platformrequest',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='users.subscriptionoffer'),
        ),
        migrations.AddField(
            model_name='platformrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mvola', 'MVola'), ('paypal', 'PayPal'), ('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='platformrequest',
            name='request_type',
            field=models.CharField(choices=[('device_deletion', "Suppression d'appareil"), ('activation', "Activation d'abonnement"), ('payment', 'Paiement direct')], max_length=20),
        ),
    ]
