# Generated by Django 6.0.4 on 2026-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_platformrequest_contact_email_platformrequest_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
