# Generated by Django 6.0.4 on 2026-07-27 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_chatmessage_edited_at_chatmessage_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='tickets/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='users.magasinprofile')),
                ('sales', models.ManyToManyField(blank=True, related_name='tickets', to='users.sale')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
