# Generated by Django 6.0.4 on 2026-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_platformrequest_consumed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
