# Generated by Django 6.0.4 on 2026-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_device_latitude_device_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginevent',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
