# Generated by Django 6.0.4 on 2026-08-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_loginevent_logged_out_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoffer',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, help_text="Durée de l'offre en mois (1, 2, 3...)"),
        ),
    ]
