# Generated by Django 6.0.4 on 2026-08-05 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_subscriptionoffer_duration_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('product', 'Product'), ('user', 'User'), ('chat', 'Chat'), ('transfer', 'Transfer'), ('movement', 'Movement'), ('caisse', 'Caisse'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='CaisseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée')], default='open', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opening_note', models.CharField(blank=True, max_length=255, null=True)),
                ('closing_note', models.CharField(blank=True, max_length=255, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisse_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_sessions', to='users.magasinprofile')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisse_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CaisseMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrée'), ('out', 'Sortie')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisse_movements', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisse_movements', to='users.magasinprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='users.caissesession')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='caisse_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.caissesession'),
        ),
    ]
