# Generated by Django 6.0.4 on 2026-08-06 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_notification_notif_type_caissesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissesession',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
