# Generated by Django 6.0.4 on 2026-09-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_caissesession_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='variant_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
