# Generated by Django 6.0.4 on 2026-08-10 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_caissesession_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sold_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
