# Generated by Django 6.0.4 on 2026-09-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_sale_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='source_magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_as_source', to='users.magasinprofile'),
        ),
        migrations.AddField(
            model_name='movement',
            name='destination_magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_as_destination', to='users.magasinprofile'),
        ),
        migrations.AddField(
            model_name='movement',
            name='transfer_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
