# Generated by Django 5.2.17 on 2026-09-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_movement_note_alter_movement_variant_label'),
        ('users', '0020_movement_source_destination_transfer_batch'),
    ]

    operations = [
    ]
